In [3]:
import pandas as pd

In [4]:
pd.Series([4,7,9,8], index= ['A','B','C','D'])

A    4
B    7
C    9
D    8
dtype: int64

In [5]:
s = {
    "Name" :["Rohit", "Adi", "Roi","JD"],
    "Marks" : [47,89,69,98]
}
s1 = pd.DataFrame(s)

s1

    Name  Marks
0  Rohit     47
1    Adi     89
2    Roi     69
3     JD     98

In [6]:
lst = [['rohit',80], ["joy", 75],["roi",100]]
df = pd.DataFrame(lst, columns=["Name", "Marks"])

df

    Name  Marks
0  rohit     80
1    joy     75
2    roi    100

In [12]:
import numpy as np
df= pd.DataFrame(np.array([[2,40],[5,60],[8,80]]), columns=["A", "B"])

df

   A   B
0  2  40
1  5  60
2  8  80

In [14]:
df =pd.read_csv("studentData1.csv", encoding="latin-1")
df

    No    Student Name  Marks                     School Name
0    1     Rahul Kumar     89      Green Valley Public School
1    2     Sneha Patil     76   Sunrise English Medium School
2    3   Aditya Sharma     92       Little Flower High School
3    4     Kavya Reddy     81         National Convent School
4    5     Arjun Mehta     67             St. Josephs School
5    6      Priya Nair     95              Kendriya Vidyalaya
6    7    Manish Gupta     72             City Central School
7    8      Riya Singh     88            Oxford Public School
8    9  Sohan Kulkarni     54        Vidya Mandir High School
9   10  Pooja Deshmukh     78              Silver Oak Academy
10  11    Nikhil Verma     83           Carmel Convent School
11  12     Aditi Joshi     91             Delhi Public School
12  13    Varun Shetty     69              New Horizon School
13  14     Simran Kaur     87             Mount Carmel School
14  15    Rohan Thakur     74             Blossom High School
15  16      Shreya Rao     98       Ryan International School
16  17      Karan Jain     63          Heritage Public School
17  18      Ananya Das     82          Blue Bells High School
18  19  Abhishek Sinha     59               Springdale School
19  20  Meera Kulkarni     90  Greenwood International School

In [19]:
df =pd.read_excel("studentData1.xlsx")
df

    No    Student Name  Marks                     School Name
0    1     Rahul Kumar     89      Green Valley Public School
1    2     Sneha Patil     76   Sunrise English Medium School
2    3   Aditya Sharma     92       Little Flower High School
3    4     Kavya Reddy     81         National Convent School
4    5     Arjun Mehta     67             St. Joseph’s School
5    6      Priya Nair     95              Kendriya Vidyalaya
6    7    Manish Gupta     72             City Central School
7    8      Riya Singh     88            Oxford Public School
8    9  Sohan Kulkarni     54        Vidya Mandir High School
9   10  Pooja Deshmukh     78              Silver Oak Academy
10  11    Nikhil Verma     83           Carmel Convent School
11  12     Aditi Joshi     91             Delhi Public School
12  13    Varun Shetty     69              New Horizon School
13  14     Simran Kaur     87             Mount Carmel School
14  15    Rohan Thakur     74             Blossom High School
15  16      Shreya Rao     98       Ryan International School
16  17      Karan Jain     63          Heritage Public School
17  18      Ananya Das     82          Blue Bells High School
18  19  Abhishek Sinha     59               Springdale School
19  20  Meera Kulkarni     90  Greenwood International School

In [18]:
df =pd.read_json("data.json")
df

   id    name  marks                 school
0   1   Rahul     89    Green Valley School
1   2   Sneha     76  Sunrise Public School
2   3   Arjun     92   Little Flower School
3   4   Priya     85     Kendriya Vidyalaya
4   5   Varun     67     New Horizon School
5   6    Riya     90   Oxford Public School
6   7  Manish     72    City Central School
7   8   Aditi     95    Delhi Public School
8   9  Simran     81    Mount Carmel School
9  10   Karan     63        Heritage School

In [20]:
df

    No    Student Name  Marks                     School Name
0    1     Rahul Kumar     89      Green Valley Public School
1    2     Sneha Patil     76   Sunrise English Medium School
2    3   Aditya Sharma     92       Little Flower High School
3    4     Kavya Reddy     81         National Convent School
4    5     Arjun Mehta     67             St. Joseph’s School
5    6      Priya Nair     95              Kendriya Vidyalaya
6    7    Manish Gupta     72             City Central School
7    8      Riya Singh     88            Oxford Public School
8    9  Sohan Kulkarni     54        Vidya Mandir High School
9   10  Pooja Deshmukh     78              Silver Oak Academy
10  11    Nikhil Verma     83           Carmel Convent School
11  12     Aditi Joshi     91             Delhi Public School
12  13    Varun Shetty     69              New Horizon School
13  14     Simran Kaur     87             Mount Carmel School
14  15    Rohan Thakur     74             Blossom High School
15  16      Shreya Rao     98       Ryan International School
16  17      Karan Jain     63          Heritage Public School
17  18      Ananya Das     82          Blue Bells High School
18  19  Abhishek Sinha     59               Springdale School
19  20  Meera Kulkarni     90  Greenwood International School

In [22]:
df.head()

   No   Student Name  Marks                    School Name
0   1    Rahul Kumar     89     Green Valley Public School
1   2    Sneha Patil     76  Sunrise English Medium School
2   3  Aditya Sharma     92      Little Flower High School
3   4    Kavya Reddy     81        National Convent School
4   5    Arjun Mehta     67            St. Joseph’s School

In [24]:
df.tail()

    No    Student Name  Marks                     School Name
15  16      Shreya Rao     98       Ryan International School
16  17      Karan Jain     63          Heritage Public School
17  18      Ananya Das     82          Blue Bells High School
18  19  Abhishek Sinha     59               Springdale School
19  20  Meera Kulkarni     90  Greenwood International School

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   No            20 non-null     int64
 1   Student Name  20 non-null     object
 2   Marks         20 non-null     int64
 3   School Name   20 non-null     object
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

In [27]:
df.describe()

             No      Marks
count  20.00000  20.000000
mean   10.50000  79.400000
std     5.91608  12.419848
min     1.00000  54.000000
25%     5.75000  71.250000
50%    10.50000  81.500000
75%    15.25000  89.250000
max    20.00000  98.000000

In [29]:
df.columns

Index(['No', 'Student Name', 'Marks', 'School Name'], dtype='object')

In [30]:
df.shape

(20, 4)

In [31]:
df = pd.read_csv("https://codewithharry.nyc3.cdn.digitaloceanspaces.com/dashboard/lesson/creating-dataframes-1745077860781/1745500125912-data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [35]:
df[["Actor", "IMDb"]]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [37]:
df.loc[:5, ["Actor", "IMDb"]]

                Actor  IMDb
0      Shah Rukh Khan   7.2
1         Salman Khan   6.0
2          Aamir Khan   8.4
3       Ranbir Kapoor   5.6
4       Ranveer Singh   7.0
5  Ayushmann Khurrana   8.3

In [38]:
df.iloc[:5 ,[1,4]]

              Film  BoxOffice(INR Crore)
0          Pathaan                  1050
1  Tiger Zinda Hai                   565
2           Dangal                  2024
3       Brahmastra                   431
4        Padmaavat                   585

In [39]:
df.iloc[1,1]

'Tiger Zinda Hai'

In [40]:
df.loc[1,'Film']

'Tiger Zinda Hai'

In [41]:
df.at[1, "BoxOffice(INR Crore)"]

np.int64(565)

In [42]:
df.at[1, "Actor"]

'Salman Khan'

In [43]:
df.iat[0,4]

np.int64(1050)

In [50]:
df[(df["Year"]<2019) & (df["Actor"]=='Salman Khan') ]

         Actor             Film  Year   Genre  BoxOffice(INR Crore)  IMDb
1  Salman Khan  Tiger Zinda Hai  2017  Action                   565   6.0