## null values Cleaning

In [2]:
import pandas as pd

In [45]:
df = pd.read_csv("https://codewithharry.nyc3.cdn.digitaloceanspaces.com/dashboard/lesson/data-cleaning-preprocessing-1745500885184/1745501008647-data_cleaning_sample.csv")
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [6]:
df.shape

(9, 6)

In [7]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [8]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [9]:
df1 = df.fillna(0)

In [10]:
df1.isnull().sum()

Name         0
Age          0
City         0
Gender       0
Email        0
Join Date    0
dtype: int64

In [11]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

## duplicate

In [18]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [13]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [14]:

df1 = df.drop_duplicates()

In [15]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [21]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [22]:
df.duplicated(["Age", "Name"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [24]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [26]:
df["City"].str.contains("Delhi", case=False).sum()

np.int64(4)

In [27]:
df["Email"].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [ ]:
type(df["Email"].str.split('@'))

pandas.core.series.Series

In [44]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York    NaN  alice@example.com  01-05-2021     adult
1  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021     adult
2      Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020     adult
3  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021     adult
4    David  22.0       Mumbai    NaN  david@example.com  12-11-2019     adult
5      NaN  28.0        Delhi    NaN     eve@domain.com         NaN     adult
6    Alice  25.0     New York    NaN  alice@example.com  01-05-2021     adult
7    Alice  25.0     New York    NaN  alice@example.com  01-05-2021     adult
8  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021     adult

In [30]:
df['Age Group'] =df["Age"].apply(lambda x: "minor" if x<18 else "adult")

In [42]:
df

      Name   Age         City Gender              Email   Join Date Age Group
0    Alice  25.0     New York    NaN  alice@example.com  01-05-2021     adult
1  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021     adult
2      Bob  30.0  Los Angeles    NaN    bob@example.com  15-06-2020     adult
3  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021     adult
4    David  22.0       Mumbai    NaN  david@example.com  12-11-2019     adult
5      NaN  28.0        Delhi    NaN     eve@domain.com         NaN     adult
6    Alice  25.0     New York    NaN  alice@example.com  01-05-2021     adult
7    Alice  25.0     New York    NaN  alice@example.com  01-05-2021     adult
8  Charlie   NaN        Delhi    NaN    charlie@example  20-07-2021     adult

In [52]:
df1 = df.dropna(subset=['Gender']).copy()
df1

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [53]:
gender_map = {"M": "Male", "F": "Female"}
df1["Gender"] = df1["Gender"].map(gender_map)
df1

      Name   Age         City  Gender              Email   Join Date
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021

In [55]:


df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [60]:
df['City'] = df["City"].replace({"Delhi": "new Delhi", "Mumbai": "Mumbai"})
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN    new Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN    new Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0    new Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN    new Delhi      M    charlie@example  20-07-2021