## Sorting

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://codewithharry.nyc3.cdn.digitaloceanspaces.com/dashboard/lesson/creating-dataframes-1745077860781/1745500125912-data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df1 = df.sort_values('Year', ascending= False).copy()
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [10]:
df1.sort_values(['Year', "IMDb"],  ascending= False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [14]:
df1.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
2,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,7,Hrithik Roshan,War,2019,Action,475,6.5
4,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
8,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [15]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 2
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Actor                 12 non-null     object
 1   Film                  12 non-null     object
 2   Year                  12 non-null     int64
 3   Genre                 12 non-null     object
 4   BoxOffice(INR Crore)  12 non-null     int64
 5   IMDb                  12 non-null     float64
dtypes: float64(1), int64(2), object(3)
memory usage: 672.0+ bytes

In [18]:
df1.reset_index(drop= True, inplace= True)
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
2,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Hrithik Roshan,War,2019,Action,475,6.5
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [24]:
df1.loc[1,'Actor']

'Ranbir Kapoor'

In [25]:
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
2,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Hrithik Roshan,War,2019,Action,475,6.5
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [26]:
df.sort_values(['Year',"IMDb"])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [27]:
df.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2