## Merging & Joining Data

In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees , departments,  on='DeptID')  # inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [6]:
pd.merge(employees , departments,  on='DeptID' , how= 'right')

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [7]:
pd.merge(employees , departments , on='DeptID', how='left')

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees, departments , on='DeptID', how='outer')

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [13]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "score" : [10 ,40]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"] , 'Age' : [26,52]})

In [14]:
df1

    Name  score
0  Alice     10
1    Bob     40

In [15]:
df2

      Name  Age
0  Charlie   26
1    David   52

In [16]:
pd.concat([df1, df2])

      Name  score   Age
0    Alice   10.0   NaN
1      Bob   40.0   NaN
0  Charlie    NaN  26.0
1    David    NaN  52.0

In [17]:
pd.concat([df1, df2] ,axis=1)

    Name  score     Name  Age
0  Alice     10  Charlie   26
1    Bob     40    David   52