## Working with CSVs

In [3]:
import pandas as pd

In [8]:
df = pd.read_csv('studentData1.csv',encoding='latin1')

In [11]:
df1 = df[df['Marks']>90].copy()

In [12]:
df1

    No   Student Name  Marks                School Name
2    3  Aditya Sharma     92  Little Flower High School
5    6     Priya Nair     95         Kendriya Vidyalaya
11  12    Aditi Joshi     91        Delhi Public School
15  16     Shreya Rao     98  Ryan International School

In [ ]:
df1.to_csv('Marks90.csv', index=False)  # index=False remove the index columns

In [18]:
df = pd.read_excel('studentData1.xlsx')
df

    No    Student Name  Marks                     School Name
0    1     Rahul Kumar     89      Green Valley Public School
1    2     Sneha Patil     76   Sunrise English Medium School
2    3   Aditya Sharma     92       Little Flower High School
3    4     Kavya Reddy     81         National Convent School
4    5     Arjun Mehta     67             St. Joseph’s School
5    6      Priya Nair     95              Kendriya Vidyalaya
6    7    Manish Gupta     72             City Central School
7    8      Riya Singh     88            Oxford Public School
8    9  Sohan Kulkarni     54        Vidya Mandir High School
9   10  Pooja Deshmukh     78              Silver Oak Academy
10  11    Nikhil Verma     83           Carmel Convent School
11  12     Aditi Joshi     91             Delhi Public School
12  13    Varun Shetty     69              New Horizon School
13  14     Simran Kaur     87             Mount Carmel School
14  15    Rohan Thakur     74             Blossom High School
15  16      Shreya Rao     98       Ryan International School
16  17      Karan Jain     63          Heritage Public School
17  18      Ananya Das     82          Blue Bells High School
18  19  Abhishek Sinha     59               Springdale School
19  20  Meera Kulkarni     90  Greenwood International School

In [22]:
df1 = df[df['Marks']<60]

In [23]:
df1.to_excel('Marks35.xlsx', index=False)

In [26]:
df1

    No    Student Name  Marks               School Name
8    9  Sohan Kulkarni     54  Vidya Mandir High School
18  19  Abhishek Sinha     59         Springdale School

In [27]:
df2 = df[df['Marks']<92]

In [28]:
with pd.ExcelWriter('report.xlsx') as writer:
    df1.to_excel(writer, sheet_name='sheetZero1', index=False)
    df2.to_excel(writer, sheet_name='sheetZero2', index=False)

In [36]:
df = pd.read_json('data.json')
df

   id    name  marks                 school
0   1   Rahul     89    Green Valley School
1   2   Sneha     76  Sunrise Public School
2   3   Arjun     92   Little Flower School
3   4   Priya     85     Kendriya Vidyalaya
4   5   Varun     67     New Horizon School
5   6    Riya     90   Oxford Public School
6   7  Manish     72    City Central School
7   8   Aditi     95    Delhi Public School
8   9  Simran     81    Mount Carmel School
9  10   Karan     63        Heritage School

In [34]:
df1 = pd.json_normalize(df)

In [39]:
df = pd.read_json('data_1.json')
df = pd.json_normalize(df.to_dict())

df

,university.id,university.name,university.location.country,university.location.state,university.location.city,university.location.geo.latitude,university.location.geo.longitude,university.established,university.accreditation,university.departments,...,metadata.id,metadata.name,metadata.location,metadata.established,metadata.accreditation,metadata.departments,metadata.generated_by,metadata.generated_on,metadata.version,metadata.is_active
0,UNI-2025-IND,Ajeenkya DY Patil University,India,Maharashtra,Pune,18.5185,73.8567,2015,"[UGC, NAAC]","[{'dept_id': 'CS', 'name': 'Computer Science',...",...,NaN,NaN,NaN,NaN,NaN,NaN,Academic Management System,2025-12-15T18:45:00+05:30,1.0.0,True